# Generated by Django 4.2.13 on 2024-05-28 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cpu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        choices=[("a", "Amd"), ("i", "Intel")],
                        default="a",
                        max_length=1,
                        verbose_name="Gamintojas",
                    ),
                ),
                ("model", models.CharField(max_length=25, verbose_name="Modelis")),
                (
                    "base_speed",
                    models.CharField(max_length=5, verbose_name="Bazinis daznis"),
                ),
                ("speed", models.CharField(max_length=5, verbose_name="Dažnis")),
                (
                    "cores",
                    models.CharField(max_length=3, verbose_name="Branduolių kiekis"),
                ),
                ("threads", models.CharField(max_length=3, verbose_name="Gijų kiekis")),
                ("tdp", models.IntegerField(verbose_name="TDP")),
                ("score", models.IntegerField(verbose_name="Skaičius palyginimui")),
            ],
        ),
        migrations.CreateModel(
            name="Gpu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        choices=[("a", "Amd"), ("n", "Nvidia"), ("i", "Intel")],
                        default="a",
                        max_length=1,
                        verbose_name="Gamintojas",
                    ),
                ),
                ("model", models.CharField(max_length=5, verbose_name="Modelis")),
                (
                    "vram",
                    models.CharField(max_length=5, verbose_name="Atminties kiekis"),
                ),
                (
                    "mem_type",
                    models.CharField(max_length=7, verbose_name="Atminties tipas"),
                ),
                (
                    "power_pins",
                    models.CharField(
                        choices=[
                            ("n", "Nereikalauja papildomo maitinimo"),
                            ("6", "6 pinų"),
                            ("8", "8 pinų"),
                            ("6+6", "2 x 6 pinų"),
                            ("8+6", "8 pinų + 6 pinų"),
                            ("8+8", "2 x 8 pinų"),
                            ("12", "12 pinų"),
                        ],
                        default="n",
                        max_length=3,
                        verbose_name="Reikalaujamas connectorius",
                    ),
                ),
                ("tdp", models.IntegerField(verbose_name="TDP")),
                ("score", models.IntegerField(verbose_name="Skaičius palyginimui")),
            ],
        ),
        migrations.CreateModel(
            name="Postai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("s", "Pagalba surinkime nuo nulio"),
                            ("a", "Atnaujinimas seno kompiuterio"),
                            ("p", "Problemos su kompiuteriu"),
                            ("k", "Kiti įrenginiai"),
                            ("r", "Tematiški renginiai"),
                        ],
                        default="s",
                        max_length=1,
                        verbose_name="Kategorija",
                    ),
                ),
                ("theme", models.CharField(max_length=150, verbose_name="Tema")),
                (
                    "description",
                    models.CharField(max_length=5000, verbose_name="Aprašymas"),
                ),
                (
                    "ft_1",
                    models.ImageField(default="no_photo.jpg", upload_to="post_pics"),
                ),
                (
                    "ft_2",
                    models.ImageField(default="no_photo.jpg", upload_to="post_pics"),
                ),
                (
                    "ft_3",
                    models.ImageField(default="no_photo.jpg", upload_to="post_pics"),
                ),
                (
                    "ft_4",
                    models.ImageField(default="no_photo.jpg", upload_to="post_pics"),
                ),
                (
                    "ft_5",
                    models.ImageField(default="no_photo.jpg", upload_to="post_pics"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        default="default-user.png", upload_to="profile_pics"
                    ),
                ),
                (
                    "f_name",
                    models.CharField(max_length=30, null=True, verbose_name="Vardas"),
                ),
                (
                    "l_name",
                    models.CharField(max_length=30, null=True, verbose_name="Vardas"),
                ),
                (
                    "reg_data",
                    models.DateField(
                        auto_now_add=True, verbose_name="Registracijos data"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profilis",
                "verbose_name_plural": "Profiliai",
            },
        ),
        migrations.CreateModel(
            name="Ram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        choices=[
                            ("k", "Kingston"),
                            ("cor", "Corsair"),
                            ("cru", "Crucial"),
                            ("a", "Adata"),
                            ("amd", "AMD"),
                            ("h", "SK Hynix"),
                            ("m", "Micron"),
                            ("s", "Samsung"),
                            ("p", "Patriot"),
                        ],
                        default="k",
                        max_length=3,
                        verbose_name="Gamintojas",
                    ),
                ),
                ("model", models.CharField(max_length=5, verbose_name="Modelis")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("2", "DDR2"),
                            ("3", "DDR3"),
                            ("4", "DDR4"),
                            ("5", "DDR5"),
                        ],
                        default="4",
                        max_length=1,
                        verbose_name="Atminties tipas",
                    ),
                ),
                (
                    "speed",
                    models.CharField(max_length=4, verbose_name="Atminties greitis"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ram_kiekis",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="RAM  plokštelių kiekis"
                    ),
                ),
                (
                    "procesorius",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PCbuildingapp.cpu",
                    ),
                ),
                (
                    "profilis",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PCbuildingapp.profile",
                    ),
                ),
                (
                    "ramai",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PCbuildingapp.ram",
                    ),
                ),
                (
                    "vaizdo_plokste",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PCbuildingapp.gpu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostaiReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.TextField(
                        max_length=2000, verbose_name="Komentaras užsakymui"
                    ),
                ),
                (
                    "ft",
                    models.ImageField(default="no_photo.jpg", upload_to="review_pics"),
                ),
                (
                    "postas",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PCbuildingapp.postai",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Posto komentaras",
                "verbose_name_plural": "Posto komentarai",
            },
        ),
    ]
