# Generated by Django 4.2.13 on 2024-05-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCbuildingapp", "0003_alter_profile_f_name_alter_profile_l_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                default="media\\default-user.png", upload_to="profile_pics"
            ),
        ),
    ]
