# Generated by Django 4.2.13 on 2024-05-30 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("PCbuildingapp", "0005_alter_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="postai",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="l_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Pavardė"
            ),
        ),
    ]
