# Generated by Django 4.2.13 on 2024-05-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCbuildingapp", "0006_postai_creator_alter_profile_l_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="postai",
            name="create_data",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Sukurimo data"
            ),
        ),
    ]
