# Generated by Django 4.2.13 on 2024-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCbuildingapp", "0007_postai_create_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postai",
            name="create_data",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Sukurimo data"
            ),
        ),
    ]
