# Generated by Django 4.2.13 on 2024-05-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCbuildingapp", "0008_alter_postai_create_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="postai",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Aktyvi"),
                    ("u", "Uždaryta"),
                    ("p", "Paslėpta"),
                    ("d", "Ištrinta"),
                    ("v", "VIP"),
                ],
                default="a",
                max_length=1,
                null=True,
                verbose_name="Statusas",
            ),
        ),
    ]
