# Generated by Django 4.2.13 on 2024-06-03 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("PCbuildingapp", "0009_postai_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kaina", models.FloatField(blank=True, null=True)),
                (
                    "telefonas",
                    models.CharField(blank=True, default="+370", max_length=13),
                ),
                ("cpu_kiekis", models.IntegerField(blank=True, default=0, null=True)),
                ("gpu_kiekis", models.IntegerField(blank=True, default=0, null=True)),
                ("ram_kiekis", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "ft_1",
                    models.ImageField(
                        default="no_photo.jpg",
                        upload_to="advertisement_pics",
                        verbose_name="Paveiksliukas Nr. 1",
                    ),
                ),
                (
                    "ft_2",
                    models.ImageField(
                        default="no_photo.jpg",
                        upload_to="advertisement_pics",
                        verbose_name="Paveiksliukas Nr. 2",
                    ),
                ),
                (
                    "ft_3",
                    models.ImageField(
                        default="no_photo.jpg",
                        upload_to="advertisement_pics",
                        verbose_name="Paveiksliukas Nr. 3",
                    ),
                ),
                (
                    "ft_4",
                    models.ImageField(
                        default="no_photo.jpg",
                        upload_to="advertisement_pics",
                        verbose_name="Paveiksliukas Nr. 4",
                    ),
                ),
                (
                    "cpu_modelis",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PCbuildingapp.cpu",
                    ),
                ),
                (
                    "gpu_modelis",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PCbuildingapp.gpu",
                    ),
                ),
                (
                    "ram_modelis",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PCbuildingapp.ram",
                    ),
                ),
                (
                    "useris",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skelbimas",
                "verbose_name_plural": "Skelbimai",
            },
        ),
    ]
