# Generated by Django 4.2.13 on 2024-06-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PCbuildingapp", "0013_advertisements_aprasymas_advertisements_tema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisements",
            name="cpu_modelis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PCbuildingapp.cpu",
            ),
        ),
        migrations.AlterField(
            model_name="advertisements",
            name="gpu_modelis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PCbuildingapp.gpu",
            ),
        ),
        migrations.AlterField(
            model_name="advertisements",
            name="ram_modelis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PCbuildingapp.ram",
            ),
        ),
    ]
