# Generated by Django 4.2.13 on 2024-06-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCbuildingapp", "0014_alter_advertisements_cpu_modelis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisements",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Aktyvus"),
                    ("p", "Paslėptas"),
                    ("d", "Ištrintas"),
                    ("v", "VIP"),
                ],
                default="a",
                max_length=1,
                null=True,
                verbose_name="Statusas",
            ),
        ),
    ]
