# Generated by Django 4.2.13 on 2024-06-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCbuildingapp", "0015_advertisements_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ram",
            name="size",
            field=models.IntegerField(null=True, verbose_name="Atminties dydis"),
        ),
    ]
