# Generated by Django 4.2.13 on 2024-06-03 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("PCbuildingapp", "0016_alter_ram_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postaireview",
            name="content",
            field=models.TextField(max_length=2000, verbose_name="Komentaras postui"),
        ),
        migrations.CreateModel(
            name="AdvertisementReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.TextField(
                        max_length=2000, verbose_name="Komentaras skelbimui"
                    ),
                ),
                (
                    "advert",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PCbuildingapp.advertisements",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skelbimo komentaras",
                "verbose_name_plural": "Skelbimų komentarai",
            },
        ),
    ]
